version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: student-event-mysql
    restart: always
    environment:
      MYSQL_DATABASE: student_event_db
      MYSQL_ROOT_PASSWORD: Vishnu
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - student-event-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./Backend/student-event-management/student-event-management
      dockerfile: Dockerfile
    container_name: student-event-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: student_event_db
      DB_USER: root
      DB_PASSWORD: Vishnu
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - student-event-network

 
  frontend:
    build:
      context: ./Frontend/studenteventsimplemanagement
      dockerfile: Dockerfile
    container_name: student-event-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - student-event-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: student-event-jenkins
    restart: unless-stopped
    ports:
      - "9090:8080"   
      - "50000:50000"  
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - student-event-network

networks:
  student-event-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  jenkins-data:
    driver: local



