services:
  mysql:
    image: mysql:8.0
    container_name: student-event-mysql
    restart: always
    environment:
      MYSQL_DATABASE: student_event_db
      MYSQL_ROOT_PASSWORD: Vishnu
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql:/var/lib/mysql  # EBS volume mounted at /data
    networks:
      - student-event-network
    mem_limit: 512m
    memswap_limit: 512m
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pVishnu"]
      timeout: 20s
      retries: 10
      interval: 5s
      start_period: 30s

  backend:
    image: ${BACKEND_IMAGE:-vishnuha/student-event-backend:latest}
    container_name: student-event-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: student_event_db
      DB_USER: root
      DB_PASSWORD: Vishnu
      SPRING_PROFILES_ACTIVE: prod
    mem_limit: 768m
    memswap_limit: 768m
    depends_on:
      mysql:
        condition: service_healthy  # Wait for MySQL to be healthy
    networks:
      - student-event-network
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -lc '</dev/tcp/localhost/8080' && echo OK || exit 1"]
      timeout: 10s
      retries: 5
      interval: 10s
      start_period: 180s

  frontend:
    image: ${FRONTEND_IMAGE:-vishnuha/student-event-frontend:latest}
    container_name: student-event-frontend
    restart: always
    ports:
      - "80:80"
      - "3000:80"
    mem_limit: 256m
    memswap_limit: 256m
    depends_on:
      backend:
        condition: service_healthy  # Wait for Backend to be healthy
    networks:
      - student-event-network

networks:
  student-event-network:
    driver: bridge

volumes:
  mysql-data:
