services:
  mysql:
    image: mysql:8.0
    container_name: student-event-mysql
    restart: always
    environment:
      MYSQL_DATABASE: student_event_db
      MYSQL_ROOT_PASSWORD: Vishnu
    ports:
      - "3307:3306"
    volumes:
      - /data/mysql:/var/lib/mysql
    networks:
      - student-event-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s

  backend:
    image: vishnuha/student-event-backend:latest
    container_name: student-event-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: student_event_db
      DB_USER: root
      DB_PASSWORD: Vishnu
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - student-event-network

  frontend:
    image: vishnuha/student-event-frontend:latest
    container_name: student-event-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - student-event-network

networks:
  student-event-network:
    driver: bridge
